# Generated by Django 4.1 on 2022-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
