# Generated by Django 4.1 on 2022-08-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
