# Generated by Django 4.1 on 2022-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dasan',
            fields=[
                ('dasan_no', models.AutoField(primary_key=True, serialize=False)),
                ('used', models.IntegerField()),
            ],
            options={
                'db_table': 'dasan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('borrow_date', models.DateTimeField()),
                ('borrow_status', models.IntegerField()),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yangjae',
            fields=[
                ('yangjae_no', models.AutoField(primary_key=True, serialize=False)),
                ('used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yangjae',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
